server:
  port: 5000
xxnbr:
  kafka:
    group-id: xxnbr
    host: http://localhost:9092
  client:
    address:
      url: http://localhost:8080/addresses

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: cleanarch